### ISSUE TITLE
Facsimile skal ændres til Faksimile

### ISSUE THREAD

**Issue by Weinkouff** [Det-Kongelige-Bibliotek/Danmarks-Breve#48]
Skal rettes alle steder

**Comment by Weinkouff** [comment]
Rettes mi PDF titel

**Comment by xenma** [comment]
Couldn't find a clean solution on that, but I changed the url to faksimile, and I added a title that gets concatenated with the url, for example: Faksimile - faksimile.pdf and Tekst - /letter_books/005490285/005490285_000-L0054902850000247.pdf
