### ISSUE TITLE
Vis ikke tomme felter i metadata på brevvisning

### ISSUE THREAD

**Issue by Weinkouff** [Det-Kongelige-Bibliotek/Danmarks-Breve#49]

**Comment by siglun** [comment]
No empty fields should be shown in letter view.

**Comment by O-Zone** [comment]
Jeg g�r ud fra at jeg ikke er p� KB den dag! :-6 (Men det gl�der mig virkelig at I tager det alvorligt! :-) )

/Hasse
________________________________________
Fra: Sigfrid Lundberg [notifications@github.com]
Sendt: 23. august 2016 16:12
Til: Det-Kongelige-Bibliotek/Danmarks-Breve
Emne: Re: [Det-Kongelige-Bibliotek/Danmarks-Breve] Vis ikke tomme felter i metadata p� brevvisning (#49)

Closed #49<https://github.com/Det-Kongelige-Bibliotek/Danmarks-Breve/issues/49>.

�

**Comment by O-Zone** [comment]
Doh ... mit forrige svar var ment til en anden mail! :-I
________________________________________
Fra: Hasse Feldthaus
Sendt: 23. august 2016 19:07
Til: Det-Kongelige-Bibliotek/Danmarks-Breve
Emne: SV: [Det-Kongelige-Bibliotek/Danmarks-Breve] Vis ikke tomme felter i metadata p� brevvisning (#49)

Jeg g�r ud fra at jeg ikke er p� KB den dag! :-6 (Men det gl�der mig virkelig at I tager det alvorligt! :-) )

/Hasse
________________________________________
Fra: Sigfrid Lundberg [notifications@github.com]
Sendt: 23. august 2016 16:12
Til: Det-Kongelige-Bibliotek/Danmarks-Breve
Emne: Re: [Det-Kongelige-Bibliotek/Danmarks-Breve] Vis ikke tomme felter i metadata p� brevvisning (#49)

Closed #49<https://github.com/Det-Kongelige-Bibliotek/Danmarks-Breve/issues/49>.

�
