### ISSUE TITLE
Høj footer

### ISSUE THREAD

**Issue by Weinkouff** [Det-Kongelige-Bibliotek/Danmarks-Breve#51]

**Comment by O-Zone** [comment]
Is it still too high? I have already cut a considerable chunk of the height?

**Comment by Weinkouff** [comment]
Den bliver for høj nogle gange når man skifter side - DGJ kan demonstere :-)

**Comment by O-Zone** [comment]
Jeg er på sagen! :8ball:

**Comment by siglun** [comment]
O-Zone har fixat saken!
