### ISSUE TITLE
Citation virker ikke

### ISSUE THREAD

**Issue by Weinkouff** [Det-Kongelige-Bibliotek/Danmarks-Breve#56]

**Comment by siglun** [comment]
The reference is no improved, inasmuch as it is written as a chapter in a book.

**Comment by siglun** [comment]
The reason for limited visibility in production was the same as the one causing  empty bookmarks

**Comment by Weinkouff** [comment]
Rettes Reference

**Comment by xenma** [comment]
David updated the index and all the volumes are in there, so it works fine
